/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData caviar = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shrimp = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData seaurchin = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lobster = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData squid = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fish = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData shellfish = const IconData(0xe806, fontFamily: _kFontFam);
}
